newlint

diff --git a/.github/workflows/ansible_linter.yml b/.github/workflows/ansible_linter.yml
--- a/.github/workflows/ansible_linter.yml
+++ b/.github/workflows/ansible_linter.yml
@@ -38,41 +38,41 @@ jobs:
       #     args: " >> temp.txt"
       #     requirements_file: ""
 
-      - name: "Update python packages"
-        run: |
-          # pip install -r requirements_stable.txt
-          pip install -U ansible-lint
+      # - name: "Update python packages"
+      #   run: |
+      #     # pip install -r requirements_stable.txt
+      #     pip install -U ansible-lint
 
-      # - name: "Update ansible collections"
-      #   run: ansible-galaxy collection install -r ansible_required_collections.yml
+      # # - name: "Update ansible collections"
+      # #   run: ansible-galaxy collection install -r ansible_required_collections.yml
 
-      - name: "Run ansible-lint"
-        id: run-lint
-        run: ansible-lint > lint_tmp.txt
+      # - name: "Run ansible-lint"
+      #   id: run-lint
+      #   run: ansible-lint > lint_tmp.txt
 
-      - name: "Prettify ansible-lint output"
-        id: prettify-res
-        if: failure()
-        run: |
-          if [ -s lint_tmp.txt ]; then
-            characters_limit=1990
-            cat lint_tmp.txt | head -c 1990 | sed -e '$a\' | sed 's/"/'\''/g'
-            number_non_empty_lines=$(cat lint_tmp.txt | head -c $characters_limit | awk 'NF' | wc -l)
-            current_limit=$((characters_limit - number_non_empty_lines))
-            echo $current_limit
-            echo "d"
-            echo "GITDIFF<<EOF" >> $GITHUB_OUTPUT
-            # echo -n '```' >> $GITHUB_OUTPUT
-            cat lint_tmp.txt | head -c 1980 | sed -e '$a\' | sed 's/"/'\''/g' >> $GITHUB_OUTPUT
-            # [ $(wc -c < lint_tmp.txt) -gt $current_limit ] && echo '...```' >> $GITHUB_OUTPUT || echo '```' >> $GITHUB_OUTPUT
-            echo "EOF" >> $GITHUB_OUTPUT
-            cat $GITHUB_OUTPUT
-          fi
+      # - name: "Prettify ansible-lint output"
+      #   id: prettify-res
+      #   if: failure()
+      #   run: |
+      #     if [ -s lint_tmp.txt ]; then
+      #       characters_limit=1990
+      #       cat lint_tmp.txt | head -c 1990 | sed -e '$a\' | sed 's/"/'\''/g'
+      #       number_non_empty_lines=$(cat lint_tmp.txt | head -c $characters_limit | awk 'NF' | wc -l)
+      #       current_limit=$((characters_limit - number_non_empty_lines))
+      #       echo $current_limit
+      #       echo "d"
+      #       echo "GITDIFF<<EOF" >> $GITHUB_OUTPUT
+      #       # echo -n '```' >> $GITHUB_OUTPUT
+      #       cat lint_tmp.txt | head -c 1980 | sed -e '$a\' | sed 's/"/'\''/g' >> $GITHUB_OUTPUT
+      #       # [ $(wc -c < lint_tmp.txt) -gt $current_limit ] && echo '...```' >> $GITHUB_OUTPUT || echo '```' >> $GITHUB_OUTPUT
+      #       echo "EOF" >> $GITHUB_OUTPUT
+      #       cat $GITHUB_OUTPUT
+      #     fi
 
       # Add SLACK_API_TOKEN in dGithub secretsd
       - name: "Send Slack notifidcdation (fail)"
         id: send-fail-message
-        if: failure()
+        #if: failure()
         uses: slackapi/slack-github-action@v2.0.0
         with:
           method: chat.postMessage
@@ -85,7 +85,7 @@ jobs:
                 fields:
                   - title: "Message"
                     short: false
-                    value: "yaml[document-start]: Missing document start '---'
+                    value: "```yaml[document-start]: Missing document start '---'
                             1 copy 2.yml:1
 
                             yaml[empty-lines]: Too many blank lines (30 > 2)
@@ -170,7 +170,7 @@ jobs:
                             1 copy 3.yml:1
 
                             yaml[empty-lines]: Too many blank lines (30 > 2)
-                            1 copy 3.ym```"
+                            1 copy 3.ym ...```"
                   - value: "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Action log>"
 
 
